// <auto-generated />
using System;
using Bareeq.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bareeq.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514005958_AddBranchAndPaymentFlow")]
    partial class AddBranchAndPaymentFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bareeq.Api.Entities.Addon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Addons");

                    b.HasData(
                        new
                        {
                            Id = "strawberry",
                            Label = "Strawberry",
                            Price = 30,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "blueberry",
                            Label = "Blueberry",
                            Price = 30,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "caramel",
                            Label = "Caramel",
                            Price = 25,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "pistachio",
                            Label = "Pistachio",
                            Price = 35,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "nutella",
                            Label = "Nutella",
                            Price = 30,
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Badge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Glyph")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = "first",
                            Description = "First order placed",
                            Glyph = "✦",
                            Label = "First Sip",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "streak7",
                            Description = "7-day streak",
                            Glyph = "◔",
                            Label = "Seven Mornings",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "matcha",
                            Description = "Tried all matcha",
                            Glyph = "❋",
                            Label = "Matcha Master",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "brewbar",
                            Description = "Tried Aeropress + V60",
                            Glyph = "◐",
                            Label = "Brew Bar Initiate",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "winter",
                            Description = "3 hot chocolates",
                            Glyph = "❄",
                            Label = "Winter Ritual",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "signature",
                            Description = "Order 5 signatures",
                            Glyph = "✧",
                            Label = "House Signature",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "beans",
                            Description = "Buy 3 bean SKUs",
                            Glyph = "●",
                            Label = "Bean Collector",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "vip",
                            Description = "Reach VIP",
                            Glyph = "♛",
                            Label = "Inner Circle",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = "helwan",
                            Address = "شارع طلعت حرب، حلوان، القاهرة",
                            Hours = "Sun–Thu 8 AM–11 PM, Fri–Sat 8 AM–12 AM",
                            Label = "Helwan",
                            Latitude = 29.8416,
                            Longitude = 31.334199999999999,
                            Phone = "+20 2 2555 0101"
                        },
                        new
                        {
                            Id = "hadayek-helwan",
                            Address = "شارع الجيش، حدائق حلوان، القاهرة",
                            Hours = "Sun–Thu 8 AM–11 PM, Fri–Sat 8 AM–12 AM",
                            Label = "Hadayek Helwan",
                            Latitude = 29.8553,
                            Longitude = 31.322099999999999,
                            Phone = "+20 2 2555 0202"
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Glyph")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "signature",
                            Glyph = "✦",
                            LabelAr = "المميزة",
                            LabelEn = "Signature",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "coffee",
                            Glyph = "◐",
                            LabelAr = "قهوة",
                            LabelEn = "Coffee",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "cold",
                            Glyph = "◇",
                            LabelAr = "باردة",
                            LabelEn = "Cold",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "blended",
                            Glyph = "◯",
                            LabelAr = "مخفوقة",
                            LabelEn = "Blended",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "matcha",
                            Glyph = "❋",
                            LabelAr = "ماتشا",
                            LabelEn = "Matcha",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "refresher",
                            Glyph = "≈",
                            LabelAr = "منعشة",
                            LabelEn = "Refreshers",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "juice",
                            Glyph = "◔",
                            LabelAr = "عصائر",
                            LabelEn = "Juice",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "dessert",
                            Glyph = "❀",
                            LabelAr = "حلويات",
                            LabelEn = "Dessert",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "bakery",
                            Glyph = "❒",
                            LabelAr = "مخبوزات",
                            LabelEn = "Bakery",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "cookies",
                            Glyph = "✿",
                            LabelAr = "كوكيز",
                            LabelEn = "Cookies",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "beans",
                            Glyph = "●",
                            LabelAr = "حبوب",
                            LabelEn = "Coffee Beans",
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Coupon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExpiryText")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = "WINTER25",
                            Description = "25% off all hot chocolates",
                            ExpiryText = "Ends May 21",
                            Flavor = "burgundy",
                            Label = "Winter Warmer",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "MATCHA2x1",
                            Description = "Buy 1 matcha · get 1 free, 3–5pm",
                            ExpiryText = "Daily",
                            Flavor = "matcha",
                            Label = "Matcha Hour",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "BEANS150",
                            Description = "EGP 150 off any 250g bag",
                            ExpiryText = "Ends Jun 02",
                            Flavor = "ink",
                            Label = "Bean Drop",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "BIRTHDAY",
                            Description = "Any signature drink · birthday week",
                            ExpiryText = "Personalized",
                            Flavor = "gold",
                            Label = "On The House",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Flag")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = "fic",
                            Calories = 320,
                            CategoryId = "signature",
                            Description = "Fruity & chocolate · whipped cream cap, berries",
                            Flag = "new",
                            NameAr = "فروتي آيس شوكولاتة",
                            NameEn = "Fruity Ice Chocolate",
                            Price = 120,
                            SortOrder = 1,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "trh",
                            Calories = 90,
                            CategoryId = "signature",
                            Description = "Hibiscus, passion, lemon, soda",
                            Flag = "new",
                            NameAr = "كركديه استوائي",
                            NameEn = "Tropical Hibiscus",
                            Price = 100,
                            SortOrder = 2,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "shc",
                            Calories = 380,
                            CategoryId = "signature",
                            Description = "Winter ritual · strawberry cream, dark cocoa",
                            Flag = "winter",
                            NameAr = "شوكولاتة ساخنة بالفراولة",
                            NameEn = "Strawberry Hot Chocolate",
                            Price = 100,
                            SortOrder = 3,
                            Tone = "burgundy"
                        },
                        new
                        {
                            Id = "bhc",
                            Calories = 410,
                            CategoryId = "signature",
                            Description = "Hazelnut praline, milk foam crown",
                            Flag = "winter",
                            NameAr = "بوينو شوكولاتة ساخنة",
                            NameEn = "Bueno Hot Chocolate",
                            Price = 100,
                            SortOrder = 4,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "aero",
                            Calories = 5,
                            CategoryId = "signature",
                            Description = "Single-origin pour · clean, citric, weightless",
                            Flag = "brew",
                            NameAr = "إيروبريس",
                            NameEn = "Aeropress · Brew Bar",
                            Price = 100,
                            SortOrder = 5,
                            Tone = "ink"
                        },
                        new
                        {
                            Id = "v60",
                            Calories = 5,
                            CategoryId = "signature",
                            Description = "Chemex-style filter · slow extraction, 4 min",
                            Flag = "new",
                            NameAr = "V60",
                            NameEn = "V60 · Brew Bar",
                            Price = 120,
                            SortOrder = 6,
                            Tone = "ink"
                        },
                        new
                        {
                            Id = "mdl",
                            Calories = 240,
                            CategoryId = "coffee",
                            Description = "Medjool dates, espresso, milk, cinnamon",
                            Flag = "signature",
                            NameAr = "لاتيه التمر",
                            NameEn = "Medjool Date Latte",
                            Price = 110,
                            SortOrder = 7,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "pis",
                            Calories = 260,
                            CategoryId = "coffee",
                            Description = "Pistachio, milk, espresso, a touch of bareeq",
                            Flag = "bestseller",
                            NameAr = "لاتيه فستق",
                            NameEn = "Pistachio Latte",
                            Price = 130,
                            SortOrder = 8,
                            Tone = "pistachio"
                        },
                        new
                        {
                            Id = "spa",
                            Calories = 290,
                            CategoryId = "coffee",
                            Description = "Condensed milk, espresso, milk",
                            NameAr = "لاتيه إسباني",
                            NameEn = "Spanish Latte",
                            Price = 115,
                            SortOrder = 9,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "wmoc",
                            Calories = 310,
                            CategoryId = "coffee",
                            Description = "White chocolate, espresso, milk",
                            NameAr = "وايت موكا",
                            NameEn = "White Mocha",
                            Price = 115,
                            SortOrder = 10,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "moc",
                            Calories = 290,
                            CategoryId = "coffee",
                            Description = "Chocolate, fresh milk, espresso",
                            NameAr = "موكا",
                            NameEn = "Mocha",
                            Price = 110,
                            SortOrder = 11,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "scl",
                            Calories = 280,
                            CategoryId = "coffee",
                            Description = "Milk, espresso, salted caramel",
                            NameAr = "كراميل بالملح",
                            NameEn = "Salted Caramel Latte",
                            Price = 110,
                            SortOrder = 12,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "cap",
                            Calories = 140,
                            CategoryId = "coffee",
                            Description = "Milk, espresso, foam crown",
                            NameAr = "كابتشينو",
                            NameEn = "Cappuccino",
                            Price = 85,
                            SortOrder = 13,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "lat",
                            Calories = 200,
                            CategoryId = "coffee",
                            Description = "Fresh milk, espresso, magic",
                            NameAr = "لاتيه",
                            NameEn = "Latte",
                            Price = 100,
                            SortOrder = 14,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "cor",
                            Calories = 120,
                            CategoryId = "coffee",
                            Description = "Espresso · milk · light foam",
                            NameAr = "كورتادو",
                            NameEn = "Cortado",
                            Price = 70,
                            SortOrder = 15,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "fw",
                            Calories = 150,
                            CategoryId = "coffee",
                            Description = "Espresso · milk · velvet foam",
                            NameAr = "فلات وايت",
                            NameEn = "Flat White",
                            Price = 80,
                            SortOrder = 16,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "ccl",
                            Calories = 270,
                            CategoryId = "coffee",
                            Description = "Cinnamon, caramel, milk, espresso",
                            NameAr = "قرفة وكراميل",
                            NameEn = "Cinnamon Caramel Latte",
                            Price = 110,
                            SortOrder = 17,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "am",
                            Calories = 5,
                            CategoryId = "coffee",
                            Description = "Espresso + hot water",
                            NameAr = "أمريكانو",
                            NameEn = "Americano",
                            Price = 70,
                            SortOrder = 18,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "esp",
                            Calories = 5,
                            CategoryId = "coffee",
                            Description = "Specialty single shot",
                            NameAr = "إسبريسو",
                            NameEn = "Espresso",
                            Price = 60,
                            SortOrder = 19,
                            Tone = "ink"
                        },
                        new
                        {
                            Id = "tur",
                            Calories = 5,
                            CategoryId = "coffee",
                            Description = "Slow simmered · Brazilian + Colombian blend",
                            NameAr = "قهوة تركي",
                            NameEn = "Turkish Coffee",
                            Price = 35,
                            SortOrder = 20,
                            Tone = "ink"
                        },
                        new
                        {
                            Id = "mac",
                            Calories = 80,
                            CategoryId = "coffee",
                            Description = "Espresso · a kiss of foam",
                            NameAr = "ماكياتو",
                            NameEn = "Macchiato",
                            Price = 60,
                            SortOrder = 21,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "hcm",
                            Calories = 280,
                            CategoryId = "coffee",
                            Description = "Caramel, milk, espresso, vanilla",
                            NameAr = "كراميل ماكياتو",
                            NameEn = "Hot Caramel Macchiato",
                            Price = 115,
                            SortOrder = 22,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "iam",
                            Calories = 5,
                            CategoryId = "cold",
                            Description = "Espresso · ice · water",
                            NameAr = "أيس أمريكانو",
                            NameEn = "Iced Americano",
                            Price = 70,
                            SortOrder = 23,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "ipis",
                            Calories = 280,
                            CategoryId = "cold",
                            Description = "Pistachio, milk, espresso",
                            Flag = "bestseller",
                            NameAr = "أيس فستق",
                            NameEn = "Iced Pistachio Latte",
                            Price = 130,
                            SortOrder = 24,
                            Tone = "pistachio"
                        },
                        new
                        {
                            Id = "icm",
                            Calories = 290,
                            CategoryId = "cold",
                            Description = "Caramel, milk, espresso, vanilla",
                            NameAr = "أيس كراميل",
                            NameEn = "Iced Caramel Macchiato",
                            Price = 115,
                            SortOrder = 25,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "iwm",
                            Calories = 320,
                            CategoryId = "cold",
                            Description = "White mocha, espresso, milk",
                            NameAr = "أيس وايت موكا",
                            NameEn = "Iced Shaken White Mocha",
                            Price = 115,
                            SortOrder = 26,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "imo",
                            Calories = 300,
                            CategoryId = "cold",
                            Description = "Chocolate, espresso, milk",
                            NameAr = "أيس موكا",
                            NameEn = "Iced Mocha",
                            Price = 115,
                            SortOrder = 27,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "iscl",
                            Calories = 290,
                            CategoryId = "cold",
                            Description = "Milk, espresso, salted caramel",
                            NameAr = "أيس كراميل بالملح",
                            NameEn = "Iced Salted Caramel Latte",
                            Price = 115,
                            SortOrder = 28,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "isp",
                            Calories = 300,
                            CategoryId = "cold",
                            Description = "Milk, espresso, condensed milk",
                            NameAr = "أيس إسباني",
                            NameEn = "Iced Spanish Latte",
                            Price = 115,
                            SortOrder = 29,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "ilat",
                            Calories = 210,
                            CategoryId = "cold",
                            Description = "Milk · espresso · ice",
                            NameAr = "أيس لاتيه",
                            NameEn = "Iced Latte",
                            Price = 100,
                            SortOrder = 30,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "pcb",
                            Calories = 360,
                            CategoryId = "blended",
                            Description = "Pistachio cream, espresso, vanilla milk",
                            NameAr = "فستق بلند",
                            NameEn = "Pistachio Cream Blend",
                            Price = 130,
                            SortOrder = 31,
                            Tone = "pistachio"
                        },
                        new
                        {
                            Id = "carb",
                            Calories = 340,
                            CategoryId = "blended",
                            Description = "Caramel, milk powder, vanilla, espresso",
                            NameAr = "كراميل بلند",
                            NameEn = "Caramel Blend",
                            Price = 120,
                            SortOrder = 32,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "wmb",
                            Calories = 360,
                            CategoryId = "blended",
                            Description = "White chocolate, vanilla milk, espresso",
                            NameAr = "وايت موكا بلند",
                            NameEn = "White Mocha Blend",
                            Price = 120,
                            SortOrder = 33,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "scb",
                            Calories = 340,
                            CategoryId = "blended",
                            Description = "Salted caramel, milk, espresso, ice",
                            NameAr = "كراميل ملح بلند",
                            NameEn = "Salted Caramel Blend",
                            Price = 120,
                            SortOrder = 34,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "mob",
                            Calories = 340,
                            CategoryId = "blended",
                            Description = "Chocolate, fresh milk, espresso",
                            NameAr = "موكا بلند",
                            NameEn = "Mocha Blend",
                            Price = 120,
                            SortOrder = 35,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "lab",
                            Calories = 280,
                            CategoryId = "blended",
                            Description = "Milk, espresso, vanilla ice",
                            NameAr = "لاتيه بلند",
                            NameEn = "Latte Blend",
                            Price = 100,
                            SortOrder = 36,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "spb",
                            Calories = 320,
                            CategoryId = "blended",
                            Description = "Condensed milk, espresso, vanilla, ice",
                            NameAr = "إسباني بلند",
                            NameEn = "Spanish Blend",
                            Price = 120,
                            SortOrder = 37,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "onc",
                            Calories = 380,
                            CategoryId = "blended",
                            Description = "Oreo, Nutella, vanilla powder",
                            NameAr = "أوريو نوتيلا",
                            NameEn = "Oreo Nutella Cream",
                            Price = 100,
                            SortOrder = 38,
                            Tone = "ink"
                        },
                        new
                        {
                            Id = "svc",
                            Calories = 320,
                            CategoryId = "blended",
                            Description = "Strawberry, vanilla, ice, whipped cream",
                            NameAr = "فراولة وفانيليا",
                            NameEn = "Strawberry Vanilla Cream",
                            Price = 100,
                            SortOrder = 39,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "blu",
                            Calories = 280,
                            CategoryId = "blended",
                            Description = "Blueberries, vanilla, ice, whipped",
                            NameAr = "توت أزرق",
                            NameEn = "Blueberry",
                            Price = 89,
                            SortOrder = 40,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "hsm",
                            Calories = 220,
                            CategoryId = "matcha",
                            Description = "Japanese ceremonial matcha, condensed milk",
                            Flag = "new",
                            NameAr = "ماتشا إسباني ساخن",
                            NameEn = "Hot Spanish Matcha",
                            Price = 120,
                            SortOrder = 41,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jcsm",
                            Calories = 280,
                            CategoryId = "matcha",
                            Description = "Ceremonial grade · cream cap",
                            NameAr = "ماتشا كريم إسباني",
                            NameEn = "Japanese Cream Spanish Matcha",
                            Price = 120,
                            SortOrder = 42,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jbmc",
                            Calories = 290,
                            CategoryId = "matcha",
                            Description = "Blueberry compote, matcha, cream",
                            Flag = "new",
                            NameAr = "ماتشا توت كريم",
                            NameEn = "Japanese Blueberry Matcha Cream",
                            Price = 120,
                            SortOrder = 43,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jiwc",
                            Calories = 280,
                            CategoryId = "matcha",
                            Description = "White chocolate, ceremonial matcha, ice",
                            NameAr = "ماتشا وايت شوكولاتة بارد",
                            NameEn = "Iced White Chocolate Matcha",
                            Price = 120,
                            SortOrder = 44,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jml",
                            Calories = 180,
                            CategoryId = "matcha",
                            Description = "Ceremonial matcha, milk",
                            Flag = "signature",
                            NameAr = "ماتشا لاتيه",
                            NameEn = "Japanese Matcha Latte",
                            Price = 120,
                            SortOrder = 45,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jwmb",
                            Calories = 320,
                            CategoryId = "matcha",
                            Description = "Matcha, white chocolate, blended",
                            NameAr = "ماتشا بلند",
                            NameEn = "White Chocolate Matcha Blend",
                            Price = 120,
                            SortOrder = 46,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "jcm",
                            Calories = 280,
                            CategoryId = "matcha",
                            Description = "Milk powder, vanilla, ceremonial matcha",
                            Flag = "new",
                            NameAr = "ماتشا كريم",
                            NameEn = "Japanese Cream Matcha",
                            Price = 120,
                            SortOrder = 47,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "sbl",
                            Calories = 90,
                            CategoryId = "refresher",
                            Description = "Blue lemon, lemon, mint, soda",
                            NameAr = "ليمونادة زرقاء",
                            NameEn = "Sunshine Blue Lemonade",
                            Price = 80,
                            SortOrder = 48,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "sst",
                            Calories = 100,
                            CategoryId = "refresher",
                            Description = "Strawberry, lemon, mint, soda",
                            NameAr = "فراولة منعشة",
                            NameEn = "Sunshine Strawberry",
                            Price = 80,
                            SortOrder = 49,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "spe",
                            Calories = 100,
                            CategoryId = "refresher",
                            Description = "Peach, lemon, mint, soda",
                            NameAr = "خوخ منعش",
                            NameEn = "Sunshine Peach",
                            Price = 80,
                            SortOrder = 50,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "sbb",
                            Calories = 95,
                            CategoryId = "refresher",
                            Description = "Blueberry, lemon, mint, soda",
                            NameAr = "توت منعش",
                            NameEn = "Sunshine Blueberry",
                            Price = 80,
                            SortOrder = 51,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "spf",
                            Calories = 95,
                            CategoryId = "refresher",
                            Description = "Passion fruit soda",
                            NameAr = "باشن منعش",
                            NameEn = "Sunshine Passion Fruit",
                            Price = 80,
                            SortOrder = 52,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "slm",
                            Calories = 80,
                            CategoryId = "refresher",
                            Description = "Lemon, mint, soda",
                            NameAr = "ليمون نعناع",
                            NameEn = "Sunshine Lemon Mint",
                            Price = 80,
                            SortOrder = 53,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "pit",
                            Calories = 110,
                            CategoryId = "refresher",
                            Description = "Brewed tea, peach, ice",
                            NameAr = "شاي خوخ بارد",
                            NameEn = "Peach Iced Tea",
                            Price = 80,
                            SortOrder = 54,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "lpf",
                            Calories = 100,
                            CategoryId = "refresher",
                            Description = "Lemon, tropical fruits",
                            NameAr = "ليمون باشن",
                            NameEn = "Lemon Passion Fruit",
                            Price = 80,
                            SortOrder = 55,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "wat",
                            Calories = 110,
                            CategoryId = "juice",
                            Description = "Watermelon, sugar, ice",
                            Flag = "new",
                            NameAr = "بطيخ",
                            NameEn = "Watermelon",
                            Price = 80,
                            SortOrder = 56,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "msm",
                            Calories = 180,
                            CategoryId = "juice",
                            Description = "Fresh mango smoothie",
                            NameAr = "مانجو سموذي",
                            NameEn = "Mango Smoothie",
                            Price = 70,
                            SortOrder = 57,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "mng",
                            Calories = 130,
                            CategoryId = "juice",
                            Description = "Fresh-pressed mango",
                            NameAr = "مانجو",
                            NameEn = "Mango",
                            Price = 60,
                            SortOrder = 58,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "bsm",
                            Calories = 160,
                            CategoryId = "juice",
                            Description = "Wild blueberry, water, bareeq",
                            NameAr = "توت سموذي",
                            NameEn = "Blueberry Smoothie",
                            Price = 80,
                            SortOrder = 59,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "pfs",
                            Calories = 170,
                            CategoryId = "juice",
                            Description = "Tropical fruits, snow, glitter",
                            NameAr = "باشن سموذي",
                            NameEn = "Passion Fruit Smoothie",
                            Price = 80,
                            SortOrder = 60,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "mlm",
                            Calories = 120,
                            CategoryId = "juice",
                            Description = "Lemonade, mint, ice, water",
                            NameAr = "ليمون نعناع",
                            NameEn = "Mint Lemonade",
                            Price = 60,
                            SortOrder = 61,
                            Tone = "matcha"
                        },
                        new
                        {
                            Id = "foj",
                            Calories = 110,
                            CategoryId = "juice",
                            Description = "Fresh-pressed orange",
                            NameAr = "عصير برتقال",
                            NameEn = "Fresh Orange Juice",
                            Price = 60,
                            SortOrder = 62,
                            Tone = "orange"
                        },
                        new
                        {
                            Id = "rvc",
                            Calories = 420,
                            CategoryId = "dessert",
                            Description = "Cream cheese frosting, slow-baked",
                            Flag = "new",
                            NameAr = "ريد فيلفت",
                            NameEn = "Red Velvet Cake",
                            Price = 120,
                            SortOrder = 63,
                            Tone = "berry"
                        },
                        new
                        {
                            Id = "cck",
                            Calories = 410,
                            CategoryId = "dessert",
                            Description = "Walnut, cinnamon, cream cheese",
                            Flag = "new",
                            NameAr = "كيك جزر",
                            NameEn = "Carrot Cake",
                            Price = 120,
                            SortOrder = 64,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "ccs",
                            Calories = 380,
                            CategoryId = "dessert",
                            Description = "Plain · vanilla cream cheese",
                            NameAr = "تشيز كيك",
                            NameEn = "Classic Cheesecake",
                            Price = 80,
                            SortOrder = 65,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "tir",
                            Calories = 440,
                            CategoryId = "dessert",
                            Description = "Mascarpone, espresso, cocoa",
                            Flag = "signature",
                            NameAr = "تيراميسو",
                            NameEn = "Italian Tiramisu",
                            Price = 120,
                            SortOrder = 66,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "rhc",
                            Calories = 380,
                            CategoryId = "dessert",
                            Description = "Layered honey, sour cream",
                            NameAr = "ميدوفيك",
                            NameEn = "Russian Honey Cake",
                            Price = 90,
                            SortOrder = 67,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "ccw",
                            Calories = 430,
                            CategoryId = "dessert",
                            Description = "Chocolate cake, fresh walnut",
                            NameAr = "كيك شوكولاتة جوز",
                            NameEn = "Chocolate Walnut Cake",
                            Price = 100,
                            SortOrder = 68,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "ssc",
                            Calories = 410,
                            CategoryId = "dessert",
                            Description = "Burnt basque · roasted, jus",
                            NameAr = "سان سيباستيان",
                            NameEn = "San Sebastian Cheesecake",
                            Price = 90,
                            SortOrder = 69,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "tms",
                            Calories = 480,
                            CategoryId = "bakery",
                            Description = "Tuna, vegetables, mayo, cheese, brown",
                            Flag = "new",
                            NameAr = "تونة ساندويتش",
                            NameEn = "Tuna Melt Sandwich",
                            Price = 90,
                            SortOrder = 70,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "don",
                            Calories = 320,
                            CategoryId = "bakery",
                            Description = "Glazed, fresh-fried",
                            Flag = "new",
                            NameAr = "دونات",
                            NameEn = "American Donuts",
                            Price = 80,
                            SortOrder = 71,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "but",
                            Calories = 280,
                            CategoryId = "bakery",
                            Description = "Layers of cultured butter",
                            NameAr = "كرواسون زبدة",
                            NameEn = "Butter Croissant",
                            Price = 50,
                            SortOrder = 72,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "pic",
                            Calories = 380,
                            CategoryId = "bakery",
                            Description = "Butter croissant, pistachio cream",
                            Flag = "signature",
                            NameAr = "كرواسون فستق",
                            NameEn = "Pistachio Croissant",
                            Price = 100,
                            SortOrder = 73,
                            Tone = "pistachio"
                        },
                        new
                        {
                            Id = "ssw",
                            Calories = 420,
                            CategoryId = "bakery",
                            Description = "Chicken, cheese, lettuce, pepper, mayo",
                            NameAr = "ساندويتش تركي",
                            NameEn = "Turkish Chicken Sandwich",
                            Price = 95,
                            SortOrder = 74,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "tcc",
                            Calories = 380,
                            CategoryId = "bakery",
                            Description = "Croissant, cheese, Turkish chicken, lettuce",
                            NameAr = "كرواسون جبن",
                            NameEn = "Turkish Cheese Croissant",
                            Price = 85,
                            SortOrder = 75,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "nuc",
                            Calories = 360,
                            CategoryId = "bakery",
                            Description = "Butter croissant, Nutella",
                            NameAr = "كرواسون نوتيلا",
                            NameEn = "Nutella Croissant",
                            Price = 80,
                            SortOrder = 76,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "cir",
                            Calories = 380,
                            CategoryId = "bakery",
                            Description = "Soft cinnamon cake roll",
                            NameAr = "سينامون رول",
                            NameEn = "Cinnamon Roll",
                            Price = 80,
                            SortOrder = 77,
                            Tone = "gold"
                        },
                        new
                        {
                            Id = "svck",
                            Calories = 220,
                            CategoryId = "cookies",
                            Description = "White & Belgian chocolate, cinnamon",
                            NameAr = "كوكيز فانيليا",
                            NameEn = "Spice Vanilla Cookies",
                            Price = 70,
                            SortOrder = 78,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "nuck",
                            Calories = 240,
                            CategoryId = "cookies",
                            Description = "Nutella centre · soft bake",
                            NameAr = "كوكيز نوتيلا",
                            NameEn = "Nutella Cookies",
                            Price = 70,
                            SortOrder = 79,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "kic",
                            Calories = 250,
                            CategoryId = "cookies",
                            Description = "Kinder · milk chocolate",
                            NameAr = "كوكيز كيندر",
                            NameEn = "Kinder Cookies",
                            Price = 85,
                            SortOrder = 80,
                            Tone = "cream"
                        },
                        new
                        {
                            Id = "orc",
                            Calories = 230,
                            CategoryId = "cookies",
                            Description = "House blend · double choc",
                            NameAr = "كوكيز كلاسيك",
                            NameEn = "Original Cookie",
                            Price = 70,
                            SortOrder = 81,
                            Tone = "coffee"
                        },
                        new
                        {
                            Id = "btr",
                            CategoryId = "beans",
                            Description = "Brazilian + Colombian · finely ground · 250g",
                            Flag = "new",
                            NameAr = "بن تركي",
                            NameEn = "Turkish Coffee Blend",
                            Price = 270,
                            SortOrder = 82,
                            Tone = "burgundy"
                        },
                        new
                        {
                            Id = "bmw",
                            CategoryId = "beans",
                            Description = "Brazil + Colombia · whole bean · 250g",
                            Flag = "signature",
                            NameAr = "ميلكي واي",
                            NameEn = "Milky Way Blend",
                            Price = 450,
                            SortOrder = 83,
                            Tone = "burgundy"
                        },
                        new
                        {
                            Id = "bbz",
                            CategoryId = "beans",
                            Description = "Single-origin · 100% Arabica · 250g",
                            NameAr = "بن برازيلي",
                            NameEn = "Brazilian Black Diamond",
                            Price = 550,
                            SortOrder = 84,
                            Tone = "burgundy"
                        },
                        new
                        {
                            Id = "bet",
                            CategoryId = "beans",
                            Description = "Yirgacheffe · floral, citrus, jasmine · 250g",
                            Flag = "bestseller",
                            NameAr = "بن إثيوبي",
                            NameEn = "Ethiopian Specialty",
                            Price = 650,
                            SortOrder = 85,
                            Tone = "burgundy"
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Milk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Milks");

                    b.HasData(
                        new
                        {
                            Id = "fresh",
                            Delta = 0,
                            Label = "Fresh whole",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "skim",
                            Delta = 0,
                            Label = "Skim",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "oat",
                            Delta = 15,
                            Label = "Oat",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "almond",
                            Delta = 15,
                            Label = "Almond",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "coconut",
                            Delta = 15,
                            Label = "Coconut",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchId")
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("DeliveryFee")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Subtotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineTotal")
                        .HasColumnType("integer");

                    b.Property<string>("MilkId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SizeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderItemAddon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddonId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AddonLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AddonPrice")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemAddons");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ReviewedBy");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.SizeOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = "single",
                            Delta = 0,
                            Label = "Single",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "double",
                            Delta = 15,
                            Label = "Double",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "grand",
                            Delta = 25,
                            Label = "Grand",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.SubscriptionPerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("SubscriptionPerks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlanId = "daily",
                            SortOrder = 1,
                            Text = "15% off all extras"
                        },
                        new
                        {
                            Id = 2,
                            PlanId = "daily",
                            SortOrder = 2,
                            Text = "Skip days anytime"
                        },
                        new
                        {
                            Id = 3,
                            PlanId = "daily",
                            SortOrder = 3,
                            Text = "Free pastry every 7th"
                        },
                        new
                        {
                            Id = 4,
                            PlanId = "beans",
                            SortOrder = 1,
                            Text = "New origin each month"
                        },
                        new
                        {
                            Id = 5,
                            PlanId = "beans",
                            SortOrder = 2,
                            Text = "Tasting notes card"
                        },
                        new
                        {
                            Id = 6,
                            PlanId = "beans",
                            SortOrder = 3,
                            Text = "Free shipping"
                        },
                        new
                        {
                            Id = 7,
                            PlanId = "brewbar",
                            SortOrder = 1,
                            Text = "Reserved stool"
                        },
                        new
                        {
                            Id = 8,
                            PlanId = "brewbar",
                            SortOrder = 2,
                            Text = "Cupping invite"
                        },
                        new
                        {
                            Id = 9,
                            PlanId = "brewbar",
                            SortOrder = 3,
                            Text = "VIP shortcut"
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.SubscriptionPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = "daily",
                            Description = "A drink a day · pick 7 weekly favorites",
                            Label = "The Daily",
                            Price = 1490,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "beans",
                            Description = "250g specialty beans, monthly",
                            Label = "The Bean Drop",
                            Price = 890,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "brewbar",
                            Description = "Eight pour-overs at the counter",
                            Label = "The Brew Bar",
                            Price = 2200,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Tier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            Id = "bronze",
                            Label = "Bronze",
                            MaxPoints = 250,
                            MinPoints = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "silver",
                            Label = "Silver",
                            MaxPoints = 750,
                            MinPoints = 250,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "gold",
                            Label = "Gold",
                            MaxPoints = 1800,
                            MinPoints = 750,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "vip",
                            Label = "VIP",
                            MaxPoints = 9999,
                            MinPoints = 1800,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.TierPerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.ToTable("TierPerks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SortOrder = 1,
                            Text = "Birthday drink",
                            TierId = "bronze"
                        },
                        new
                        {
                            Id = 2,
                            SortOrder = 2,
                            Text = "Free Wi-Fi lounge",
                            TierId = "bronze"
                        },
                        new
                        {
                            Id = 3,
                            SortOrder = 1,
                            Text = "10% off pastries",
                            TierId = "silver"
                        },
                        new
                        {
                            Id = 4,
                            SortOrder = 2,
                            Text = "Free milk upgrade",
                            TierId = "silver"
                        },
                        new
                        {
                            Id = 5,
                            SortOrder = 1,
                            Text = "Free drink weekly",
                            TierId = "gold"
                        },
                        new
                        {
                            Id = 6,
                            SortOrder = 2,
                            Text = "Priority brew bar",
                            TierId = "gold"
                        },
                        new
                        {
                            Id = 7,
                            SortOrder = 3,
                            Text = "Cupping invites",
                            TierId = "gold"
                        },
                        new
                        {
                            Id = 8,
                            SortOrder = 1,
                            Text = "Concierge ordering",
                            TierId = "vip"
                        },
                        new
                        {
                            Id = 9,
                            SortOrder = 2,
                            Text = "Reserved seat",
                            TierId = "vip"
                        },
                        new
                        {
                            Id = 10,
                            SortOrder = 3,
                            Text = "Beans drop · first access",
                            TierId = "vip"
                        },
                        new
                        {
                            Id = 11,
                            SortOrder = 4,
                            Text = "Annual roastery dinner",
                            TierId = "vip"
                        });
                });

            modelBuilder.Entity("Bareeq.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastStreakAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Sparkles")
                        .HasColumnType("integer");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Earned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Redeemed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoupons");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Address", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Item", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Order", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Bareeq.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bareeq.Api.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderItemAddon", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.OrderItem", "OrderItem")
                        .WithMany("Addons")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderPayment", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Bareeq.Api.Entities.OrderPayment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bareeq.Api.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy");

                    b.Navigation("Order");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.SubscriptionPerk", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Perks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.TierPerk", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Tier", "Tier")
                        .WithMany("Perks")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserBadge", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bareeq.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserCoupon", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Coupon", "Coupon")
                        .WithMany("UserCoupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bareeq.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.UserFavorite", b =>
                {
                    b.HasOne("Bareeq.Api.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bareeq.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Coupon", b =>
                {
                    b.Navigation("UserCoupons");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.OrderItem", b =>
                {
                    b.Navigation("Addons");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Perks");
                });

            modelBuilder.Entity("Bareeq.Api.Entities.Tier", b =>
                {
                    b.Navigation("Perks");
                });
#pragma warning restore 612, 618
        }
    }
}
